---
- hosts: all
#  remote_user: unixuser 
  serial: 10
  strategy: free
  become: yes
  become_method: sudo
  vars:
    #variable needed during node installation
    var_node: /tmp
  roles:
    - prepatching
    - patching
    - postpatching

